/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalgui;

import javax.swing.table.DefaultTableModel;
import static proyectofinalgui.RegisClasificacion.listaclasificacion;

 class ConsulClasificacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsulClasificacion
     */
    public ConsulClasificacion() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        
        for(int i =0; i < listaclasificacion.size(); i++){
            modelo.addRow(new Object[] {String.valueOf(listaclasificacion.get(i).idclasificacion),String.valueOf(listaclasificacion.get(i).clasificacion)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscarclasificacionTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Clasificacion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 6, -1, 63));
        getContentPane().add(buscarclasificacionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 87, 249, 40));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 87, -1, 40));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 87, 115, 40));

        jTable1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Clasificacion", "Clasificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 153, -1, 126));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalgui/batman-dark-4k-4s.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -30, 670, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelo2 = (DefaultTableModel) this.jTable1.getModel();
        
        modelo2.setRowCount(0);
        
        if(this.buscarclasificacionTxt.getText().equals(""))
        {
            for(int i =0; i < listaclasificacion.size(); i++)
            {
               modelo2.addRow(new Object[] {String.valueOf(listaclasificacion.get(i).idclasificacion),String.valueOf(listaclasificacion.get(i).clasificacion)});
            }            
        }
        else
        {
            for(int i =0; i < listaclasificacion.size(); i++)
            {
              String empList = listaclasificacion.get(i).clasificacion.toLowerCase();
              String textoBusqueda = this.buscarclasificacionTxt.getText().toLowerCase();
              boolean resultado = empList.contains(textoBusqueda);
              
              if(resultado == true)
              {
                  modelo2.addRow(new Object[] {String.valueOf(listaclasificacion.get(i).idclasificacion),String.valueOf(listaclasificacion.get(i).clasificacion)});
              }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarclasificacionTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
