/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalgui;

import javax.swing.table.DefaultTableModel;
import static proyectofinalgui.RegisCliente.lista;

/**
 *
 * @author LENOVO
 */
public class ConsulCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsulCliente
     */
    public ConsulCliente() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) this.jTable3.getModel();
        
        for(int i =0; i < lista.size(); i++){
            modelo.addRow(new Object[] {String.valueOf(lista.get(i).codigo),String.valueOf(lista.get(i).nombre), String.valueOf(lista.get(i).edad), String.valueOf(lista.get(i).sexo),String.valueOf(lista.get(i).telefono),String.valueOf(lista.get(i).direccion)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        BuscarClienteTxt = new javax.swing.JTextField();
        BuscarClTxt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Consulta de Clientes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 27, -1, 52));

        BuscarClienteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClienteTxtActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarClienteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 246, 34));

        BuscarClTxt.setBackground(new java.awt.Color(102, 153, 255));
        BuscarClTxt.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        BuscarClTxt.setText("Buscar");
        BuscarClTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarClTxtActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarClTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 89, -1, 34));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 90, 119, 33));

        jTable3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Edad", "Sexo", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 157, 623, 164));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalgui/batman-dark-4k-4s.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -30, 650, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarClienteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClienteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarClienteTxtActionPerformed

    private void BuscarClTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarClTxtActionPerformed
        DefaultTableModel modelo2 = (DefaultTableModel) this.jTable3.getModel();
        
        modelo2.setRowCount(0);
        
        if(this.BuscarClienteTxt.getText().equals(""))
        {
            for(int i =0; i < lista.size(); i++)
            {
                modelo2.addRow(new Object[] {String.valueOf(lista.get(i).codigo),String.valueOf(lista.get(i).nombre), String.valueOf(lista.get(i).edad), String.valueOf(lista.get(i).sexo),String.valueOf(lista.get(i).telefono),String.valueOf(lista.get(i).direccion)});
            }            
        }
        else
        {
            for(int i =0; i < lista.size(); i++)
            {
              String empList = lista.get(i).nombre.toLowerCase();
              String textoBusqueda = this.BuscarClienteTxt.getText().toLowerCase();
              boolean resultado = empList.contains(textoBusqueda);
              
              if(resultado == true)
              {
                  modelo2.addRow(new Object[] {String.valueOf(lista.get(i).codigo),String.valueOf(lista.get(i).nombre), String.valueOf(lista.get(i).edad), String.valueOf(lista.get(i).sexo),String.valueOf(lista.get(i).telefono),String.valueOf(lista.get(i).direccion)});
              }
            }
        }

        

    }//GEN-LAST:event_BuscarClTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarClTxt;
    private javax.swing.JTextField BuscarClienteTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
