/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalgui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import static proyectofinalgui.RegisClasificacion.listaclasificacion;
import static proyectofinalgui.RegisGenero.listagenero;


public class RegisPelicula extends javax.swing.JInternalFrame {

    static ArrayList<Pelicula> listapelicula = new ArrayList<Pelicula>();

    /**
     * Creates new form RegisPelicula
     */
    public RegisPelicula() {
        initComponents();

        this.cbogenero.removeAllItems();
        this.cboclasificacion.removeAllItems();
        this.cbogenero.addItem("Seleccione un Genero");
        this.cboclasificacion.addItem("Seleccione una Clasificacion");

        cargargenero();
        cargarclasificacion();

        DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();

        for (int i = 0; i < listapelicula.size(); i++) {
            modelo.addRow(new Object[]{String.valueOf(listapelicula.get(i).idpelicula), String.valueOf(listapelicula.get(i).pelicula), String.valueOf(listapelicula.get(i).generop), String.valueOf(listapelicula.get(i).clasificacionp), String.valueOf(listapelicula.get(i).estreno)});
        }
    }

    private void cargargenero() {
        for (int i = 0; i < listagenero.size(); i++) {

            cbogenero.addItem(listagenero.get(i).genero);

        }
    }

    private void cargarclasificacion() {
        for (int i = 0; i < listaclasificacion.size(); i++) {

            cboclasificacion.addItem(listaclasificacion.get(i).clasificacion);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        peliculaTxt = new javax.swing.JTextField();
        idpeliculaTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        cbogenero = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboclasificacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resgistro de Peliculas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 6, -1, 48));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Pelicula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 124, 145, 26));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Pelicula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 185, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Estreno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 312, 147, -1));

        rbSi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbSi.setForeground(new java.awt.Color(255, 255, 255));
        rbSi.setText("Si");
        rbSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSiActionPerformed(evt);
            }
        });
        getContentPane().add(rbSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 310, -1, -1));

        rbNo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rbNo.setForeground(new java.awt.Color(255, 255, 255));
        rbNo.setText("No");
        rbNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActionPerformed(evt);
            }
        });
        getContentPane().add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 310, -1, -1));

        peliculaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaTxtActionPerformed(evt);
            }
        });
        getContentPane().add(peliculaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 186, 259, 26));

        idpeliculaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpeliculaTxtActionPerformed(evt);
            }
        });
        idpeliculaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idpeliculaTxtKeyTyped(evt);
            }
        });
        getContentPane().add(idpeliculaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 124, 259, 26));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 178, -1, -1));

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 124, 139, -1));

        jTable2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pelicula", "Nombre Pelicula", "Genero", "Clasificacion", "Estreno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 426, 627, 144));

        cbogenero.setEditable(true);
        cbogenero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbogenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbogeneroActionPerformed(evt);
            }
        });
        getContentPane().add(cbogenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 241, 190, 38));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genero");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 244, -1, 28));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clasificacion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 247, -1, -1));

        cboclasificacion.setEditable(true);
        cboclasificacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cboclasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboclasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(cboclasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 241, 228, 38));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 6, 90, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 6, 86, -1));
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalgui/batman-dark-4k-4s.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -30, 810, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peliculaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaTxtActionPerformed

    private void idpeliculaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpeliculaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpeliculaTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (this.idpeliculaTxt.getText().equals("") || this.peliculaTxt.getText().equals("") || this.cbogenero.getSelectedItem().equals("") || this.cboclasificacion.getSelectedItem().equals("")) {

            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS ESPACIOS", null, JOptionPane.ERROR_MESSAGE);

        } else if (!this.rbSi.isSelected() && !this.rbNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS ESPACIOS", null, JOptionPane.ERROR_MESSAGE);
        } else {

            String estreno = "";
            if (this.rbSi.isSelected()) {
                estreno = "Si";
            }
            if (this.rbNo.isSelected()) {
                estreno = "No";
            }
            
    
            
            

            DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();

            modelo.addRow(new Object[]{this.idpeliculaTxt.getText(), this.peliculaTxt.getText(), this.cbogenero.getSelectedItem(), this.cboclasificacion.getSelectedItem(), estreno});

            listapelicula.clear();

            for (int i = 0; i < this.jTable2.getRowCount(); i++) {
                listapelicula.add(new Pelicula(Integer.parseInt(String.valueOf(this.jTable2.getValueAt(i, 0))), String.valueOf(this.jTable2.getValueAt(i, 1)), String.valueOf(this.jTable2.getValueAt(i, 2)), String.valueOf(this.jTable2.getValueAt(i, 3)), String.valueOf(this.jTable2.getValueAt(i, 4))));
            }

            JOptionPane.showMessageDialog(null, "Su Registro Fue Exitoso");

            idpeliculaTxt.setText("");
            peliculaTxt.setText("");
            this.rbNo.setSelected(false);
            this.rbSi.setSelected(false);
            this.cbogenero.setSelectedIndex(0);
            this.cboclasificacion.setSelectedIndex(0);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbogeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbogeneroActionPerformed


    }//GEN-LAST:event_cbogeneroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void rbSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSiActionPerformed
        this.rbNo.setSelected(false);
    }//GEN-LAST:event_rbSiActionPerformed

    private void rbNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActionPerformed
        this.rbSi.setSelected(false);
    }//GEN-LAST:event_rbNoActionPerformed

    private void idpeliculaTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idpeliculaTxtKeyTyped
        int tecla = evt.getKeyChar();

        boolean num = tecla >= 48 && tecla <= 57;

        if (!(num)) {
            evt.consume();
        }
    }//GEN-LAST:event_idpeliculaTxtKeyTyped

    private void cboclasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboclasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboclasificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Id;
    private javax.swing.JComboBox<String> cboclasificacion;
    private javax.swing.JComboBox<String> cbogenero;
    private javax.swing.JTextField idpeliculaTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField peliculaTxt;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbSi;
    // End of variables declaration//GEN-END:variables
}
