/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalgui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static proyectofinalgui.RegisCliente.lista;

/**
 *
 * @author LENOVO
 */
public class RegisGenero extends javax.swing.JInternalFrame {

    static ArrayList<Genero> listagenero = new ArrayList<Genero>();

    /**
     * Creates new form RegisGenero
     */
    public RegisGenero() {
        initComponents();

        DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();

        for (int i = 0; i < listagenero.size(); i++) {
            modelo.addRow(new Object[]{String.valueOf(listagenero.get(i).idgenero), String.valueOf(listagenero.get(i).genero)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        GeneroTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        RegistarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 85, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro Genero");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Genero:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        GeneroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroTxtActionPerformed(evt);
            }
        });
        GeneroTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GeneroTxtKeyTyped(evt);
            }
        });
        getContentPane().add(GeneroTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 186, 25));

        jTable2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Genero", "Nombre Genero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 689, 134));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 102, 139, -1));

        RegistarCliente.setBackground(new java.awt.Color(102, 153, 255));
        RegistarCliente.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        RegistarCliente.setText("Registrar");
        RegistarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(RegistarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 156, 139, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalgui/batman-dark-4k-4s.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -30, 720, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegistarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarClienteActionPerformed
        //

        if ( this.GeneroTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS ESPACIOS", null, JOptionPane.ERROR_MESSAGE);
        } else {
            
   

            DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();
            
            int newCode = 1;
        if (modelo.getRowCount() > 0) {
            int lastCode = Integer.parseInt(modelo.getValueAt(modelo.getRowCount() - 1, 0).toString());
            newCode = lastCode + 1;
        }

            modelo.addRow(new Object[]{String.valueOf(newCode), this.GeneroTxt.getText()});

            listagenero.clear();

            for (int i = 0; i < this.jTable2.getRowCount(); i++) {
                listagenero.add(new Genero(Integer.parseInt(String.valueOf(this.jTable2.getValueAt(i, 0))), String.valueOf(this.jTable2.getValueAt(i, 1))));
            }

            JOptionPane.showMessageDialog(null, "Su Registro Fue Exitoso");

            
            GeneroTxt.setText("");

        }


    }//GEN-LAST:event_RegistarClienteActionPerformed

    private void GeneroTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GeneroTxtKeyTyped
        int tecla = evt.getKeyChar();

        boolean may = tecla >= 65 && tecla <= 90;
        boolean min = tecla >= 97 && tecla <= 122;
        boolean espacio = tecla == 32;

        if (!(may || min || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_GeneroTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GeneroTxt;
    private javax.swing.JButton RegistarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
