/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package proyectofinalgui;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class RegisCliente extends javax.swing.JInternalFrame {

    static ArrayList<Cliente> lista = new ArrayList<Cliente>();
  
    /**
     * Creates new form RegisCliente
     */
    public RegisCliente() {
        initComponents();
        
       
        

        DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();

        for (int i = 0; i < lista.size(); i++) {
            modelo.addRow(new Object[]{String.valueOf(lista.get(i).codigo), String.valueOf(lista.get(i).nombre), String.valueOf(lista.get(i).edad), String.valueOf(lista.get(i).sexo), String.valueOf(lista.get(i).telefono), String.valueOf(lista.get(i).direccion)});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        RegistarCliente = new javax.swing.JButton();
        EdadTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TelefonoTxt = new javax.swing.JTextField();
        DireccionTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setBorder(null);
        setForeground(java.awt.Color.white);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sexo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 225, 92, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 267, 92, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 311, -1, -1));

        NombreTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTxtKeyTyped(evt);
            }
        });
        getContentPane().add(NombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 143, 218, 25));

        RegistarCliente.setBackground(new java.awt.Color(102, 153, 255));
        RegistarCliente.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        RegistarCliente.setText("Registrar");
        RegistarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(RegistarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 233, 139, 48));

        EdadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadTxtActionPerformed(evt);
            }
        });
        EdadTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadTxtKeyTyped(evt);
            }
        });
        getContentPane().add(EdadTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 182, 218, 25));

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 159, 139, 48));

        TelefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoTxtActionPerformed(evt);
            }
        });
        TelefonoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoTxtKeyTyped(evt);
            }
        });
        getContentPane().add(TelefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 268, 218, 25));

        DireccionTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionTxtKeyTyped(evt);
            }
        });
        getContentPane().add(DireccionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 312, 218, 25));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 140, 92, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Edad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 180, 92, 24));

        jTable2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Edad", "Sexo", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 391, 840, 134));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registro de Clientes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 46, -1, -1));

        rbMasculino.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rbMasculino.setForeground(new java.awt.Color(255, 255, 255));
        rbMasculino.setText("Masculino");
        getContentPane().add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 225, -1, -1));

        rbFemenino.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        rbFemenino.setForeground(new java.awt.Color(255, 255, 255));
        rbFemenino.setText("Femenino");
        rbFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeninoActionPerformed(evt);
            }
        });
        getContentPane().add(rbFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 225, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinalgui/batman-dark-4k-4s.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarClienteActionPerformed
        // obterner los datos del cliente y guardarlos en un arrayList
        
                                                   

    if (this.NombreTxt.getText().isEmpty() || this.EdadTxt.getText().isEmpty() || this.TelefonoTxt.getText().isEmpty() || this.DireccionTxt.getText().isEmpty() || (!this.rbMasculino.isSelected() && !this.rbFemenino.isSelected())) {
        JOptionPane.showMessageDialog(null, "DEBE LLENAR TODOS LOS ESPACIOS", null, JOptionPane.ERROR_MESSAGE);
    } else {
        String genero = "";

        if (this.rbMasculino.isSelected()) {
            genero = "Masculino";
        } else if (this.rbFemenino.isSelected()) {
            genero = "Femenino";
        }

        DefaultTableModel modelo = (DefaultTableModel) this.jTable2.getModel();

        int newCode = 1;
        if (modelo.getRowCount() > 0) {
            int lastCode = Integer.parseInt(modelo.getValueAt(modelo.getRowCount() - 1, 0).toString());
            newCode = lastCode + 1;
        }

        modelo.addRow(new Object[]{String.valueOf(newCode), this.NombreTxt.getText(), this.EdadTxt.getText(), genero, this.TelefonoTxt.getText(), this.DireccionTxt.getText()});

        lista.clear();

        for (int i = 0; i < this.jTable2.getRowCount(); i++) {
            lista.add(new Cliente(Integer.parseInt(String.valueOf(this.jTable2.getValueAt(i, 0))), String.valueOf(this.jTable2.getValueAt(i, 1)), Integer.parseInt(String.valueOf(this.jTable2.getValueAt(i, 2))), String.valueOf(this.jTable2.getValueAt(i, 3)), String.valueOf(this.jTable2.getValueAt(i, 4)), String.valueOf(this.jTable2.getValueAt(i, 5))));
        }

        JOptionPane.showMessageDialog(null, "Su Registro Fue Exitoso");

        NombreTxt.setText("");
        EdadTxt.setText("");
        this.rbMasculino.setSelected(false);
        this.rbFemenino.setSelected(false);
        TelefonoTxt.setText("");
        DireccionTxt.setText("");
    }




    }//GEN-LAST:event_RegistarClienteActionPerformed

    private void EdadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadTxtActionPerformed

    }//GEN-LAST:event_EdadTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TelefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoTxtActionPerformed

    private void NombreTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTxtKeyTyped
        int tecla = evt.getKeyChar();

        boolean may = tecla >= 65 && tecla <= 90;
        boolean min = tecla >= 97 && tecla <= 122;
        boolean espacio = tecla == 32;

        if (!(may || min || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreTxtKeyTyped

    private void DireccionTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionTxtKeyTyped

    }//GEN-LAST:event_DireccionTxtKeyTyped

    private void EdadTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadTxtKeyTyped
        int tecla = evt.getKeyChar();

        boolean num = tecla >= 48 && tecla <= 57;

        if (!(num)) {
            evt.consume();
        }

        if (this.EdadTxt.getText().trim().length() == 2)
            evt.consume();
    }//GEN-LAST:event_EdadTxtKeyTyped

    private void TelefonoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoTxtKeyTyped
        int tecla = evt.getKeyChar();

        boolean num = tecla >= 48 && tecla <= 57;

        if (!(num)) {
            evt.consume();
        }


    }//GEN-LAST:event_TelefonoTxtKeyTyped

    private void rbFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemeninoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DireccionTxt;
    private javax.swing.JTextField EdadTxt;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton RegistarCliente;
    private javax.swing.JTextField TelefonoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
